# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
alias vi="nvim"
alias vim="nvim"

alias ag="alias | grep"

export EDITOR="vim"
export VISUAL="$EDITOR"

# Enable vi mode
bindkey -v

# But then re-enable search
# Ctrl+R: reverse search
bindkey '^R' history-incremental-search-backward

# Ctrl+A: beginning of line
bindkey '^A' beginning-of-line

# Ctrl+E: end of line
bindkey '^E' end-of-line

# Ctrl+K: kill to end of line
bindkey '^K' kill-line

# Ctrl+U: kill to beginning of line
bindkey '^U' backward-kill-line

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
export PATH="/opt/homebrew/opt/openjdk/bin:/opt/homebrew/opt/helm@3/bin:$PATH"
export CPPFLAGS="-I/opt/homebrew/opt/openjdk/include"
# export PATH="/opt/homebrew/opt/openjdk@21/bin:$PATH"
# export PATH="/opt/homebrew/opt/node@20/bin:$PATH"
export PATH="/opt/homebrew/opt/go@1.23/bin:$PATH"

export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export PATH=/Users/vtatai/.tiup/bin:$HOME/.local/bin:$PATH

# Source machine-specific settings if available
[[ -f ~/.zshrc.local ]] && source ~/.zshrc.local

