#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#
#zmodload zsh/zprof

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
alias aliasgrep='alias | grep'

if [[ "$OSX" == "1" ]]
then
  export JAVA8_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home
# export JAVA_HOME=$JAVA8_HOME
  export M3_HOME=/usr/local/Cellar/maven/3.3.3/
  export ANT_HOME=~/tools/ant
  export AKKA_HOME=~/tools/akka
  export ROO_HOME=~/tools/spring-roo
  export GRADLE_HOME=~/tools/gradle
  export ACTIVATOR_HOME=~/tools/activator
  export HORNETQ_HOME=~/tools/hornetq
  #export CATALINA_HOME=~/tools/tomcat
  export VM_TOOLS_HOME=~/vocado/tools
  export GRAILS_HOME=~/tools/grails
  export MAVEN_HOME=~/tools/maven
fi
export MAVEN_OPTS="-Xmx3048m -Xss128m -XX:MaxMetaspaceSize=1512m -XX:+CMSClassUnloadingEnabled"

export SPRING_HOME=~/tools/spring


# Setting editor for git / svn
export VISUAL=vim
export EDITOR=vim

setopt rmstarsilent

# Speed up git autocomplete
__git_files () { 
  _wanted files expl 'local files' _files     
}

# XCode 5 hides these away:
if [[ "$OSX" == "1" ]]
then
  export C_INCLUDE_PATH="$(xcrun --show-sdk-path)/usr/include"
  export CPLUS_INCLUDE_PATH="$(xcrun --show-sdk-path)/usr/include"
  export LIBRARY_PATH="$(xcrun --show-sdk-path)/usr/lib:$(xcrun --show-sdk-path)/usr/lib/system:$LIBRARY_PATH" 
fi

if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

bindkey '^R' history-incremental-pattern-search-backward
bindkey '^[[A' up-line-or-search
bindkey '^[[B' down-line-or-search
bindkey '^E' end-of-line
bindkey '^E' vi-end-of-line
bindkey '^A' beginning-of-line
bindkey '^A' vi-beginning-of-line

alias killall-tomcat='ps axu | grep [t]omcat | grep [j]ava | sed ''s/[a-z]* *\([0-9]*\) .*/\1/g'' | xargs kill'
alias killall-tomcat9='ps axu | grep [t]omcat | grep [j]ava | sed ''s/[a-z]* *\([0-9]*\) .*/\1/g'' | xargs kill -9'

# Makes the ^ symbol work again for Git
setopt NO_NOMATCH

# jEnv
if [[ "$OSX" == "1" ]]
then
  export PATH="$HOME/.jenv/bin:$PATH" 
  eval "$(jenv init -)"
fi

# top
alias top='top -o cpu'

alias carbon='python /opt/graphite/bin/carbon-cache.py'
alias graphite-web='python /opt/graphite/bin/run-graphite-devel-server.py --port 8880 /opt/graphite'
alias ppjson='python -m json.tool'

# Fitbit aliases
# test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
source /etc/bashrc_fitbit
export THRIFT_CLI_PATH=~/src/fit/weightsite/sortinghat/thrifts/server/src/main/thrift:~/src/fit/weightsite/core/thrift/rpc/thrifts/src/main/thrift:~/src/fit/weightsite/microservice-example/zoo/thrifts/server/src/main/thrift:~/src/fit/weightsite/microservice-example/common/thrifts/src/main/thrift
export AWS_ROLE=Experimentation_Platform_Team 
export AWS_ACCOUNT=304992127519
export VAULT_ADDR=https://gcp-vault.site-ops.fitbit.com:8200

#export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home

# NVM
# Disabled since it slows down significantly the shell
#export NVM_DIR="$HOME/.nvm"
#. "/usr/local/opt/nvm/nvm.sh"
#zprof

# Python virtualenvwrapper
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/src
source /usr/local/bin/virtualenvwrapper.sh

# NVM settings
export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/usr/local/opt/nvm/etc/bash_completion" ] && . "/usr/local/opt/nvm/etc/bash_completion"  # This loads nvm bash_completion

# BEGIN ANSIBLE MANAGED BLOCK
XCODE="$(xcode-select -p 2>/dev/null || echo /Applications/Xcode.app/Contents/Developer)"
# JAVA_HOME="$(/usr/libexec/java_home -v 1.8)"; export JAVA_HOME
# PATH="${HOME}/bin:${HOME}/.local/bin:${HOME}/Library/Python/3.7/bin:${HOME}/Library/Python/2.7/bin:${JAVA_HOME}/bin:/usr/local/gnu/bin:/usr/local/bin:/usr/local/sbin:${PATH}"; export PATH
MANPATH="/usr/local/gnu/man:/usr/local/share/man:/usr/share/man:${XCODE}/Toolchains/XcodeDefault.xctoolchain/usr/share/man:${XCODE}/usr/share/man"; export MANPATH
HOMEBREW_CASK_OPTS="--appdir=/Applications"; export HOMEBREW_CASK_OPTS
HOMEBREW_NO_ENV_FILTERING=1; export HOMEBREW_NO_ENV_FILTERING
HOMEBREW_NO_AUTO_UPDATE=1; export HOMEBREW_NO_AUTO_UPDATE
HOMEBREW_NO_UPDATE_CLEANUP=1; export HOMEBREW_NO_UPDATE_CLEANUP
# END ANSIBLE MANAGED BLOCK

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
